import Layout from "@/components/layout";
import { client } from "@/libs/client";
import Head from "next/head";

export default function Home({ blog }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="HOME">
        <h1>過去の投稿</h1>
        {blog.map((blog) => (
          <li key={blog.id}>{blog.title}</li>
        ))}
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog" });
  return {
    props: {
      blog: data.contents,
    },
  };
};
